desc dual;
select * from dual;
select -10, abs(-10) from dual;
select 34.5678, floor(34.5678) from dual;
select 34.5678, round(34.5678) from dual;
select 34.5678, round(34.5678,2) from dual;
select 34.5678, round(34.5678,-1) from dual;
select trunc(34.5678,2), trunc(34.5678,-1), trunc(34.5678) from dual;
select mod(27,2), mod(27,5), mod(27,7) from dual;
select * from emp where mod(empno,2)=1;
select 'Welcome to Oracle', upper('Welcome to Oracle') from dual;
select 'Welcome to Oracle', lower('Welcome to Oracle') from dual;
select 'WELCOME TO ORACLE', initcap('WELCOME TO ORACLE') from dual;
select empno, ename, job from emp where lower(job)='manager';
select length('oracle'), length('오라클') from dual;
select lengthb('oracle'), lengthb('오라클') from dual;
select substr('Welcome to Oracle',4,3) from dual;
select substr('Welcome to Oracle',-4,3) from dual;
select substr(hiredate,1,2) 년도, substr(hiredate,4,2) 달 from emp;
select * from emp where substr(hiredate,4,2)='09';
select * from emp where substr(hiredate,1,2)='87';
select * from emp where substr(ename,-1,1)='E';
select substr('Welcome to Oracle',3,4), substrb('Welcome to Oracle',3,4) from dual;
select substr('웰컴투오라클',3,4), substrb('웰컴투오라클',3,4) from dual;
select instr('WELCOME TO ORACLE','O') from dual;
select instr('WELCOME TO ORACLE','O',6,2) from dual;
select instr('데이터베이스','이',3,1), instrb('데이터베이스','이',3,1) from dual;
select lpad('Oracle',20,'#') from dual;
select rpad('Oracle',20,'#') from dual;
select ltrim('   Oracle   ') from dual;
select rtrim('   Oracle   ') from dual;
select trim ('a' from 'aaaaOracleaaaa') from dual;
select trim('    Oracle    ') from dual;
select sysdate from dual;
select sysdate-1 어제, sysdate 오늘, sysdate+1 내일 from dual;
select hiredate, round(hiredate, 'month') from emp;
select hiredate, trunc(hiredate, 'month') from emp;
select ename, sysdate, hiredate, months_between(sysdate, hiredate) from emp;
select ename, sysdate, hiredate, trunc(months_between(sysdate, hiredate)) from emp;
select ename, hiredate, add_months(hiredate,6) from emp;
select sysdate, next_day(sysdate,'수요일') from dual;
select hiredate, last_day(hiredate) from emp;
select sysdate, to_char(sysdate, 'YYYY-MM-DD') from dual;
select hiredate, to_char(hiredate, 'YYYY-MM-DD DAY') from emp;
select hiredate, to_char(hiredate, 'YY/MON/DD DY') from emp;
select to_char(sysdate, 'YYYY-MM-DD, HH24:MM:SS') from dual;
select to_char(1230000) from dual;
select ename, sal, to_char(sal, 'L999,999') from emp;
select to_char(123456, '000000000'), to_char(123456, '999,999,999') from dual;
select ename, hiredate from emp where hiredate=to_date(19810220, 'YYYYMMDD');
select trunc(sysdate-to_date('2008/01/01', 'YYYY/MM/DD')) from dual;
select to_number('20,000','99,999') - to_number('10,000','99,999') from dual;
select ename, sal, comm, sal*12+comm, nvl(comm,0), sal*12+nvl(comm,0) from emp order by job;
select ename, deptno, decode(deptno, 10, 'ACCOUNTING', 20, 'RESEARCH', 30, 'SALES', 40, 'OPERATIONS') as dname from emp;
select empno, ename, job, sal, decode(job, 'ANALYST', 1.05*sal, 'SALESMAN', 1.1*sal, 'MANAGER', 1.15*sal, 'CLERK', 1.2*sal) as upsal from emp;
select ename, deptno, case when deptno=10 then 'ACCOUNTING' when deptno=20 then 'RESEARCH' when deptno=30 then 'SALES' when deptno=40 then 'OPERATIONS' end as dname from emp;